kernel:
  id: kernel-1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    should-unregister-on-shutdown: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    ip-address: YOUR_INSTANCE_IP
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}

aws:
  bedrock:
    region: us-east-1   #Change to your actual Bedrock region
    credentials:
      accessKeyId: YOUR_AWS_ACCESS_KEY_ID
      secretAccessKey: YOUR_AWS_SECRET_ACCESS_KEY
server:
  port: 8080