kernel:
  base-url: http://localhost:8080

spring:
  application:
    name: nvidia-agent

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    should-unregister-on-shutdown: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    ip-address: YOUR_IP

nvidia:
  api:
    base-url: https://integrate.api.nvidia.com/v1
    model: nvidia/llama-3.1-nemotron-nano-8b-v1
    api-key: ${NVIDIA_API_KEY}

web:
  allowed-origins: http://ec2-13-233-77-128.ap-south-1.compute.amazonaws.com:5173
